services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    ports:
      - "8081:8081"
      - "8083:8083"
      - "9092:9092"
      - "2181:2181"
      - "3030:3030"
    environment:
      -REST_PORT: "0"
      -RUNTESTS: "0"
      -CONNECT_PORT: "0"
      -ADV_HOST: "127.0.0.1"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - "9200:9200"
    environment:
       - discovery.type=single-node
       - xpack.security.enabled=false
       - xpack.security.http.ssl.enabled=false